categories_bert = [
    "Food and Beverage",
    "Animals and Wildlife",
    "Plants and Nature",
    "Home and Living",
    "Transportation and Travel",
    "Technology and Electronics",
    "Sports and Recreation",
    "Clothing and Accessories",
    "Health and Medicine",
    "Art and Entertainment",
    "Education and Learning",
    "Occupations and Professions",
    "Science and Technology",
    "History and Culture",
    "Emotions and Abstract Concepts"
]

categories_fast = {
    "Food and Beverage": ["apple", "burger", "pizza", "sushi", "salad"],
    "Animals and Wildlife": ["dog", "cat", "elephant", "tiger", "sparrow"],
    "Plants and Nature": ["tree", "flower", "moss", "fern", "cactus"],
    "Home and Living": ["chair", "table", "lamp", "bed", "couch"],
    "Transportation and Travel": ["car", "airplane", "bicycle", "train", "ship"],
    "Technology and Electronics": ["computer", "smartphone", "robot", "television", "camera"],
    "Sports and Recreation": ["soccer", "basketball", "yoga", "cycling", "swimming"],
    "Clothing and Accessories": ["shirt", "dress", "hat", "shoes", "watch"],
    "Health and Medicine": ["doctor", "hospital", "vaccine", "exercise", "diet"],
    "Art and Entertainment": ["painting", "music", "cinema", "dance", "theater"],
    "Education and Learning": ["book", "school", "teacher", "science", "mathematics"],
    "Occupations and Professions": ["engineer", "artist", "chef", "nurse", "teacher"],
    "Science and Technology": ["physics", "chemistry", "biology", "astronomy", "engineering"],
    "History and Culture": ["museum", "tradition", "civilization", "monument", "language"],
    "Emotions and Abstract Concepts": ["happiness", "freedom", "love", "peace", "justice"]
}

categories_fast2 = [
    "Food and Beverage",
    "Animals and Wildlife",
    "Plants and Nature",
    "Home and Living",
    "Transportation and Travel",
    "Technology and Electronics",
    "Sports and Recreation",
    "Clothing and Accessories",
    "Health and Medicine",
    "Art and Entertainment",
    "Education and Learning",
    "Occupations and Professions",
    "Science and Technology",
    "History and Culture",
    "Emotions and Abstract Concepts"
]

categories_word2vec = [
    "Food and Beverage",
    "Animals and Wildlife",
    "Plants and Nature",
    "Home and Living",
    "Transportation and Travel",
    "Technology and Electronics",
    "Sports and Recreation",
    "Clothing and Accessories",
    "Health and Medicine",
    "Art and Entertainment",
    "Education and Learning",
    "Occupations and Professions",
    "Science and Technology",
    "History and Culture",
    "Emotions and Abstract Concepts"
]

categories_mulberry = [
    "Alphabet", "Descriptive Position", "Descriptive State", 
    "Healthcare Medical conditions", "Plants and Trees", "Descriptive Direction", 
    "Leisure Toys", "Number Activity", "Religion Festival", "Religion General", 
    "Electrical TV", "Sport", "Transport Air", "People Feelings", "Descriptive Time", 
    "Healthcare Grooming items", "People Profession", "Healthcare Body parts", 
    "Food Nuts", "Transport Road", "Religion Person", "Animal Spiders and Insects", 
    "Animal Mammal", "Food Fruit", "Drink Type", "Tools Workshop", "Animal Habitat", 
    "Work and School Stationery", "Sport Accessories", "Building Furniture", 
    "Leisure Games", "Military", "Computer Icon", "Art Making", 
    "Work and School Timetable", "Building School", "Food Vegetables and salads", 
    "Science", "People Relationship", "Healthcare Medical items", "People Descriptive", 
    "Building Garden and farm", "Food Meat", "Food Breads and baking", 
    "Food Kitchen actions", "Food Kitchen items", "Celebration Item", "Money", 
    "Food Meals and snacks", "Science Eco", "Building Contents", 
    "Animal Activity Grooming", "Healthcare Grooming activities", "Electrical General", 
    "Holiday and travel", "Clothes Accessories", "Animal Features", "Clothes General", 
    "Communication Aid", "Animal Birds", "Animal Activity Feeding", "Art Colour", 
    "Building Equipment and devices", "Transport Water", "Celebration Event", 
    "Descriptive Quantity", "Clothes Jewellery", "Food Sweets and desserts", 
    "Descriptive Shape", "Food Dairy", "Food Feeding and eating", "Electrical Media", 
    "Food Diet", "Drink Containers and measures", "Building Public", "Food Ingredients", 
    "Building Structure", "Work and School Education", "Animal Reptiles and Amphibians", 
    "Electrical Phone", "Food Poultry", "Leisure General", "Building Household tasks", 
    "Building Shop", "Environment Weather", "Science Astronomy", "Electrical Computer", 
    "Country Maps", "Animal Crustacean and Molluscs", "Clothes Sport", "Music Instrument", 
    "Communication Signs", "Animal Fish and Marine mammals", "Work and School Subjects", 
    "Drink Actions", "Drink Description", "Animal Other Invertebrates", "Food Eggs", 
    "Number", "People Actions", "Country Flags", "Building Residential", "Tools Garden", 
    "Verb", "Communication Conversation", "Politics", "Question", "Leisure Playground", 
    "Food Pastas and rice", "Building Office and factory", "Transport Space", 
    "Food Vegetables and salad", "Food Fish and seafood", "Food Festival", 
    "Transport Rail", "Animal Activity Misc", "Tools Actions"
]